name: Rust

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        target: 
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true

    - name: Install build dependencies (Linux)
      if: runner.os == 'Linux' && matrix.target == 'i686-unknown-linux-gnu'
      run: sudo apt-get update && sudo apt-get install -y gcc-multilib libc6-dev-i386

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-rust-binary-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/
